spring:
  #thymeleaf
  thymeleaf: 
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  #durid 数据库连接池
  datasource: 
    url: jdbc:mysql://dev.yonyouccs.com:3001/custom-zjtl?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: devmysql
    password: DG3kCZ2Jcmpm
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 100
    initialSize: 100
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  #rabbitmq
  rabbitmq: 
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener: 
      simple: 
        concurrency: 10 #消费者数量
        max-concurrency: 10
        prefetch: 1 #消费者每次从队列获取的消息数量
        auto-startup: true #消费者自动启动
        default-requeue-rejected: true #消费失败，自动重新入队
    template: 
      retry: 
        enabled: true   #启用发送重试
        initial-interval: 000 
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
 
#mybatis  
mybatis:
    type-aliases-package: com.xwj.entity
    configuration: 
        map-underscore-to-camel-case: true #下划线转驼峰
        default-fetch-size: 100
        default-statement-timeout: 3000
    mapperLocations: classpath:com/xwj/sec/dao/*.xml
    
#redis
redis: 
  host: localhost
  port: 6379
  timeout: 10
  password: 
  poolMaxTotal: 100
  poolMaxIdle: 100
  poolMaxWait: 3000

    
